// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwakqkrhiirykjwpnsgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3YWtxa3JoaWlyeWtqd3Buc2d0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjI5NTgsImV4cCI6MjA2NjY5ODk1OH0.xKTKL_VYAHS4okilcN3FV2iLwVo2g5tKK4OUk-TmvVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});